services:
  whisper:
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    ports:
      - "9000:8000"
    volumes:
      - whisper-hf-cache:/home/ubuntu/.cache/huggingface/hub

volumes:
  whisper-hf-cache:
